apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: feed-agg
build:
  artifacts:
  - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/feed-agg
    kaniko:
      reproducible: true
      singleSnapshot: true
      useNewRun: true
      whitelistVarRun: true
      image: gcr.io/kaniko-project/executor:latest
      registryMirror: mirror.gcr.io
  cluster:
    pullSecretName: kaniko-secret
    pullSecretPath: kaniko-secret
    namespace: skaffold
deploy:
  kubeContext: kind-cluster30
  kustomize:
    paths:
      - kustomize/overlays/cluster30
